export const ADD_ARTICLE = "ADD_ARTICLE";
export const UPDATE_EMP_NUMBER = "UPDATE_EMP_NUMBER";
export const UPDATE_HOUR_OBJECT = "UPDATE_HOUR_OBJECT";
export const UPDATE_COLOR= "UPDATE_COLOR";
export const UPDATE_JOBS_ARRAY = "UPDATE_JOBS_ARRAY";
export const UPDATE_JOBS = "UPDATE_JOBS";
export const REMOVE_HOUR = "REMOVE_HOUR";
export const ADD_HOUR = "ADD_HOUR";
export const INITIALIZE_JOBS_ARRAY = "INITIALIZE_JOBS_ARRAY"
export const INITIALIZE_SHIFTS_ARRAY = "INITIALIZE_SHIFTS_ARRAY"
export const UPDATE_SHIFTS_ARRAY = "UPDATE_SHIFTS_ARRAY";
export const UPDATE_SERVER_HOUR = "UPDATE_SERVER_HOUR"

export const UPDATE_OPERATOR = "UPDATE_OPERATOR"
export const UPDATE_WORKCELL = "UPDATE_WORKCELL"
export const UPDATE_SHIFT = "UPDATE_SHIFT"
export const UPDATE_PARTNUMBER = "UPDATE_PARTNUMBER"
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT"
